modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/teamauroramods/${repo}/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Team Aurora"
credits = "ebo2022"
description = "An expansion for Minecraft's hot and cold areas."
displayURL = "https://discord.gg/BgE4EpP"
#updateJSONURL = ""
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.1.1,)"
ordering = "BEFORE"
side = "BOTH"